spring:
  application:
    name: code-packet-service

  profiles:
    active: development-local
  datasource:
    code-packet:
      url: "root:root@tcp(127.0.0.1:3306)/file_manager?loc=Local&parseTime=true&maxAllowedPacket=104857599"
      maxIdleConn: 10
      maxOpenConn: 10
      connMaxLifetime: 1800000

server:
  port: 8090

logging:
  level: debug
  file: logs/file-tools.log